[package]
name = "fuse"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[build-dependencies]
sass-rs = "0.2.2"